### ISSUE TITLE
ids are not preserved on rebuild

### ISSUE THREAD

**Issue by apevec** [rdo-infra/puppet-dlrn#12]
After latest DLRN server rebuild user ids got mixed up due to different creation sequence, luckily most matched but /home/promoter/ ended up as:
drwx------. 3 fedora-rawhide-master fedora-rawhide-master  4096 Mar 23 09:54 promoter

We could either reserve ids or re-create home directories: the latter would work for promoter and rdo-admin users where we do not store any date, but what about homedirs for DLRN instances?

**Comment by javierpena** [comment]
We are actually doing that in puppet-dlrn, but only for the worker home directories -> https://github.com/rdo-infra/puppet-dlrn/blob/master/manifests/worker.pp#L93-L97 . I'll extend that to rdoinfo and promoter.

**Comment by apevec** [comment]
One more, promote.log needs to be owned by promoter user.

**Comment by amoralej** [comment]
I can taking care of this

**Comment by amoralej** [comment]
promote.sh is executed with sudo so it should work fine anyway

Current implementation of worker.pp only executes chown if owner for base homedir is wrong. If homedir is ok chown is not executed. We should evaluate how long takes a find command in a worker homedir.

**Comment by amoralej** [comment]
As https://ci.centos.org/job/rdo-promote-repo-promote-mitaka/41/console promoter.sh is executed with sudo to root so it should work fine. In fact, in order to create the symlink we need root or worker user, so promote.log should not be owned by promoter in any case.

**Comment by apevec** [comment]
Sorry for confusion! I was looking at promote.log which was not updated but actual promotion log is promote-${LINKNAME}.log !
