### ISSUE TITLE
Many empty delorean-logs

### ISSUE THREAD

**Issue by apevec** [rdo-infra/puppet-dlrn#17]
[centos-master@trunk delorean-logs]$ find . -size 0 |wc -l
6253
Could be when flock is hit but afaict LOGFILE should not be touched in that case?

**Comment by apevec** [comment]
* Fixup until figured out:
find . -size 0 -exec rm {} \;

**Comment by javierpena** [comment]
This happens during the logrotate execution. I'm trying to figure out why, and the fix for it.

**Comment by javierpena** [comment]
After some checks, it looks like logrotate doesn't like the file name format for Delorean logs, which includes a timestamp, and will not be able to properly manage them. The alternative will be to drop logrotate config files and just set a daily cron job to remove files older than 2 days, for example.

**Comment by apevec** [comment]
:+1: for the expiration cron job

**Comment by javierpena** [comment]
Fixed by https://github.com/rdo-infra/puppet-dlrn/commit/801aed8f082a7d33ddfef0d9d78677c26412fece
