### ISSUE TITLE
run-dlrn.sh support for standalone console use-case

### ISSUE THREAD

**Issue by apevec** [rdo-infra/puppet-dlrn#18]
e.g. running with --recheck

**Comment by apevec** [comment]
* run-dlrn.sh w/o parameters as currently used, for period cron job
* run-dlrn,sh with parameters, assume console foreground execution
Patch coming.

**Comment by javierpena** [comment]
Fixed by https://github.com/rdo-infra/puppet-dlrn/issues/19
