### ISSUE TITLE
Add CentOS Virt SIG to deps repos to get qemu-kvm-ev

### ISSUE THREAD

**Issue by javierpena** [rdo-infra/puppet-dlrn#2]
(comes from https://github.com/redhat-openstack/delorean-instance/issues/22)

More info: https://github.com/redhat-openstack/website/issues/245

**Comment by apevec** [comment]
Added in centos-release-openstack-mitaka:

https://github.com/apevec/centos-release-openstack/commit/ebd91a4c7dc8c5a722026b4075bb262286b45c77

**Comment by apevec** [comment]
BTW neither hard dep in openstack-nova-compute nor soft-dep via Packstack is needed, yum install qemu-kvm will install qemu-kvm-ev if available: https://review.openstack.org/303483

**Comment by amoralej** [comment]
Tested. With current version of centos-release-openstack-mitaka we get the right version of qemu-kvm, qemu-kvm-ev

**Comment by javierpena** [comment]
This was be fixed by https://review.rdoproject.org/r/1936
