### ISSUE TITLE
Add support to manage both dlrn primary and secondary server

### ISSUE THREAD

**Issue by amoralej** [rdo-infra/puppet-dlrn#25]
In a close future, DLRN infra will be composed of two different servers:

1. Build server: is the one in charge of:
  - Doing the actual builds periodically.
  - Synchronizing it to server trunk.rdoproject.org.

2. Hashed repos servers (trunk.rdoproject.org). This server:
  - Serves build reports.
  - Serves hashed repos.
  - Redirect consistent/current-passed-ci/current-tripleo to buildlogs
  - Could be used as secondary build server to perform builds in case of primary build server is down (I'm not sure if this is realistic as buildlogs couldn't synchronize from it and promotion jobs probably will not work also)

In puppet-dlrn we should cover the configuration of both servers.

**Comment by javierpena** [comment]
We've never used the backup server as a build server, and as you say it won't be possible to do it with the new architecture, but it doesn't hurt to keep on configuring it as if it could happen.

**Comment by javierpena** [comment]
Fixed by https://github.com/rdo-infra/puppet-dlrn/pull/27
