### ISSUE TITLE
Log permission errors

### ISSUE THREAD

**Issue by dmsimard** [rdo-infra/puppet-dlrn#37]
As seen in /var/spool/mail/root

    error: skipping "/home/centos-mitaka/delorean-logs/delorean-run.1460057401.log" because parent directory has insecure permissions (It's world writable or writable by group which is not "root") Set "su" directive in config file to tell logrotate which user/group should be used for rotation.

(metric ton of these for all the workers)

**Comment by javierpena** [comment]
Those errors are caused by old logrotate.d config entries still present in the public server. I've removed them, and we should not see those errors anymore.
