### ISSUE TITLE
New DLRN instance with tags=newton-uc

### ISSUE THREAD

**Issue by apevec** [rdo-infra/puppet-dlrn#41]
Part of https://trello.com/c/guK9Ag12/157-dlrn-builds-must-reflect-what-is-tested-upstream
Related rdoinfo change https://review.rdoproject.org/r/1730

* create new DLRN instance as centos-newton with tags=newton-uc
* bootstrap it
* symlink it as centos7-master, move tags=newton to e.g. centos7-master-head

master-head should be also --head-only and lower frequency to save resource, while still providing us pre-warning, same as Fedora instances: https://github.com/rdo-infra/puppet-dlrn/issues/38

**Comment by apevec** [comment]
Initial bootstrap repo is https://trunk.rdoproject.org/centos7-new/

**Comment by javierpena** [comment]
Instance is now running, visible at https://trunk.rdoproject.org/centos7-master . Closing.
