### ISSUE TITLE
Daily mails for root Subject: Cron <root@n30> /usr/local/bin/update-web-index.sh

### ISSUE THREAD

**Issue by apevec** [rdo-infra/puppet-dlrn#42]
Need to redirect to log or /dev/null in that cron job

**Comment by apevec** [comment]
Same for rdoinfo cron job, generating hourly emails Subject: Cron <rdoinfo@n30> /usr/local/bin/rdoinfo-update.sh

**Comment by javierpena** [comment]
http://review.rdoproject.org/r/1791 should fix this.
