### ISSUE TITLE
Manage symlink from centos7-master -> centos7

### ISSUE THREAD

**Issue by dmsimard** [rdo-infra/puppet-dlrn#6]
We have repositories under centos7-mitaka, centos7-liberty and so on. centos7-master would make sense for consistency and expectations.

**Comment by apevec** [comment]
NB applied manually on trunk.rdo

**Comment by javierpena** [comment]
Fixed by https://github.com/rdo-infra/puppet-dlrn/commit/6a7611cc577be66c7149ada4bda129dd92743c4d
